#!/usr/bin/env node

'use strict';

const mkdirp = require('mkdirp');
const spawn = require('child-process-promise').spawn;
const fs = require('fs-extra');
const path = require('path');
const glob = require('glob-promise');
const _ = require('lodash');
const chokidar = require('chokidar');

mkdirp.sync('target/classes');
mkdirp.sync('target/test-classes');

function execution(args) {
  const scalaVersion = args.scala || '2.12.2';
  const scalaDepSuffix = scalaVersion.split('.').slice(0, 2).join('.');
  const specs2Artifact = args['with-specs2'] ? `org.specs2:specs2-core_${scalaDepSuffix}:${args['with-specs2']}` : '';

  const sources = args['_'] || [];

  const depArgs = args['d'];
  const verbose = args['verbose'];
  const compiler = args['compiler'];
  const useBuilder = args['use-builder'];
  const watch = args['w'];
  const userDeps = ((depArgs && typeof(depArgs) === 'string') ? [depArgs] : depArgs) || [];
  const compileDepArtifacts = [
    `org.scala-lang:scala-compiler:${scalaVersion}`];

  var compileClasspath, userClasspath;

  userDeps.push(`io.get-coursier:coursier_${scalaDepSuffix}:1.0.0-RC1`);
  userDeps.push(`io.get-coursier:coursier-cache_${scalaDepSuffix}:1.0.0-RC1`);

  if (specs2Artifact) {
    userDeps.push(specs2Artifact);
  }

  return {
    compile: () => compile(userDeps)
      .catch((error) => console.error('Error:', verbose ? error : error.name))
  }

  async function compile() {
    if (useBuilder) {
      return compileUsingBuilder();
    }

    return compileUsingCompiler();
  }

  async function compileUsingBuilder() {
    const homePath = path.resolve(__dirname, '..');

    const compileClasspath = await libsFor(homePath, 'compile');

    if (verbose) {
      console.log(compileClasspath);
    }

    // const testClasspath = await libsFor(homePath, 'test');
    const userClasspath = await libsFor(homePath, 'user');
    const scalaBuild = path.resolve(homePath, 'target/classes');

    //const libsIndex = getFilesFromIndex(path.resolve(homePath, indexFilePath));

    const commandArgs = [bootClasspathFor(compileClasspath.concat(userClasspath).concat([scalaBuild])), 'lt.indrasius.builder.ScalaBuilder'];

    if (watch) {
      commandArgs.push('--commands');
    }

    commandArgs.push(sources);

    if (watch) {
      await withExecutionTime('Build', () => watchFileChangesOn(sources, executeInteractive('java', commandArgs)));
    } else {
      await withExecutionTime('Build', () => execute('java', commandArgs));
    }
  }

  async function libsFor(packagePath, name) {
    const { dirPath, indexFilePath } = depsLibFor(name);
    const resolvedFiles = await getFilesFromIndex(path.resolve(packagePath, indexFilePath));

    //const compileClasspath = libsFor(path, 'compile');
    //const userClasspath = libsFor(path, 'user');

    return resolvedFiles.map((file) => path.resolve(packagePath, file));
  }

  async function compileUsingCompiler() {
    const mainSources = await expandSources(sources);
    const testSources = await expandTestSources(sources);

    await compileSources(mainSources, 'target/classes', 'Main compile');
    await compileSources(testSources, 'target/test-classes', 'Test compile', ['target/classes']);
    await runTests();
  }

  async function compileSources(sources, output, stepName, extraClasspath = []) {
    compileClasspath = await fetchBundleDeps('compile', {
      artifacts: compileDepArtifacts
    });

    userClasspath = await fetchBundleDeps('user', {
      artifacts: userDeps
    });

    const commandArgs = [bootClasspathFor(compileClasspath.concat(userClasspath).concat(extraClasspath)), 'scala.tools.nsc.Main', '-d', output]
      .concat(sources);

    await withExecutionTime(stepName, () => execute('java', commandArgs))
  }

  async function expandTestSources(sources) {
    return expandSources(sources, (file) => _.endsWith(file, 'Spec.scala'));
  }

  async function expandSources(sources, filter = (file) => !_.endsWith(file, 'Spec.scala')) {
    return _.flatten(await Promise.all(sources.map((source) => expandSource(source, filter))));
  }

  async function expandSource(source, filter) {
    const sourceFiles = await glob(source);

    return sourceFiles.filter(filter);
  }

  async function runTests() {
    const classpath = userClasspath.concat(['target/classes', 'target/test-classes']);

    if (verbose) {
      console.log(classpath);
    }

    const args = ['-Dfilesrunner.basepath=src', bootClasspathFor(compileClasspath), '-cp', classpath.join(':')]
      .concat(['org.specs2.runner.files', '.*Spec']);

    await withExecutionTime('Tests', () => execute('java', args));
  }

  function bootClasspathFor(items) {
    return `-Xbootclasspath/a:${items.join(':')}`;
  }

  async function fetchBundleDeps(name, { artifacts }) {
    const { dir, indexFilePath } = depsLibFor(name);

    if (fs.existsSync(indexFilePath)) {
      return getFilesFromIndex(indexFilePath);
    }

    const deps = await fetchDeps({ artifacts });

    mkdirp.sync(dir);

    const libs = await copyFilesTo(deps, dir);

    writeIndexFile(indexFilePath, artifacts, libs);

    return libs;
  }

  function writeIndexFile(indexPath, artifacts, libs) {
    return fs.writeJson(indexPath, {
      dependencies: artifacts,
      resolvedFiles: libs
    });
  }

  function depsLibFor(name) {
    const dir = `target/deps/${name}`;
    const indexFilePath = `${dir}/libs.json`;

    return {
      dir,
      indexFilePath
    };
  }

  async function getFilesFromIndex(indexPath) {
    const libsIndex = await fs.readJson(indexPath);

    return libsIndex.resolvedFiles;
  }

  function copyFilesTo(files, target) {
    return Promise.all(files.map(async(file) => copyFileTo(file, target)));
  }

  async function copyFileTo(file, target) {
    const targetName = path.join(target, path.basename(file));

    if (verbose) {
      console.log('Copy', targetName);
    }

    await fs.copy(file, targetName);

    return targetName;
  }

  async function fetchDeps({ artifacts }) {
    const command = ['fetch', '-r', 'https://oss.sonatype.org/content/repositories/releases', '-r', 'http://dl.bintray.com/scalaz/releases'].concat(artifacts);
    const collectedDeps = [];

    await executeWithOutput('./bin/coursier', command, (data) => {
      collectedDeps.push(data.toString());
    });

    const deps = collectedDeps.join('').trim().split('\n');

    return deps.length === 1 && deps[0] === '' ? [] : deps;
  }

  function execute(command, args, onOutput) {
    return executeWithOutput(command, args);
  }

  function executeInteractive(command, args, onOutput) {
    const start = new Date().getTime();
    const commandWithArgs = args.slice();

    commandWithArgs.unshift(command);

    if (verbose) {
      console.log(command, args.join(' '));
    }

    const execPromise = spawn(command, args, { stdout: 'pipe' });

    const stdout = execPromise.childProcess.stdout;
    const stderr = execPromise.childProcess.stderr;

    stdout.on('data', (data) => process.stdout.write(data));
    stderr.on('data', (data) => process.stderr.write(data));

    const stdin = execPromise.childProcess.stdin;

    return (line) => {
      stdin.write(`${line}\n`);
    };
  }

  function executeWithOutput(command, args, onOutput = (data) => process.stdout.write(data)) {
    const start = new Date().getTime();
    const commandWithArgs = args.slice();

    commandWithArgs.unshift(command);

    if (verbose) {
      console.log(command, args.join(' '));
    }

    const execPromise = spawn(command, args, { stdout: 'pipe' });

    const stdout = execPromise.childProcess.stdout;
    const stderr = execPromise.childProcess.stderr;

    stdout.on('data', onOutput);
    stderr.on('data', (data) => process.stderr.write(data));

    const processExitPromise = new Promise((fulfill, reject) => {
      try {
        execPromise.childProcess.on('exit', () => completeWith(commandWithArgs, start, () => fulfill()));
        execPromise.childProcess.on('error', (e) => completeWith(commandWithArgs, start, () => reject(e)));
      } catch (e) {
        reject(e);
      }
    });

    return execPromise.then(() => processExitPromise);
  }

  function completeWith(command, startTime, fn) {
    const execTime = new Date().getTime() - startTime;
    //console.log(`Done in ${execTime}ms`, command.join(' '));

    fn();
  }

  async function withExecutionTime(name, fn) {
    const start = new Date().getTime();

    await fn();

    const end = new Date().getTime();

    console.log(`${name} done in ${end - start}ms`);

    return;
  }
}

function watchFileChangesOn(sources, writeLine) {
  const watcher = chokidar.watch(sources, {
    persistent: true,
    ignoreInitial: true
  });

  watcher
    .on('add', (path) => writeLine(`A ${path}`))
    .on('change', (path) => writeLine(`U ${path}`))
    .on('unlink', (path) => writeLine(`D ${path}`));
}

const argOpts = {
  boolean: ['w', 'use-builder']
};

execution(require('minimist')(process.argv.slice(2), argOpts))
  .compile();
